config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :pins do
  	member do
  	  put "like", to: "pins#upvote"
  	end
  end

  root "pins#index"  
end

app/models/pin.rb
class Pin < ActiveRecord::Base
	acts_as_votable
	belongs_to :user

	has_attached_file :image, :styles => { :medium => "300x300>" }
	validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :pins

  def admin?
    admin
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  
  before_filter :configure_permitted_parameters, if: :devise_controller?

  protected
 
  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << :name
    devise_parameter_sanitizer.for(:account_update) << :name
  end
end

app/controllers/pins_controller.rb
class PinsController < ApplicationController
	before_action :find_pin, only: [:show, :edit, :update, :destroy, :upvote]
	before_action :authenticate_user!, except: [:index, :show]
	before_action :authorized_user, only: [:edit, :update, :destroy]

	def index
		@pins = Pin.all.order("created_at DESC")
	end

	def show

	end

	def new
		@pin = current_user.pins.build
	end

	def create
		@pin = current_user.pins.build(pin_params)

		if @pin.save
			redirect_to @pin, notice: "Successfully created new Pin"
		else
			render 'new'
		end
	end

	def edit

	end

	def update
		if @pin.update(pin_params)
			redirect_to @pin, notice: "Pin was Successfully updated!"
		else
			render 'edit'
		end
	end

	def destroy
		@pin.destroy
		redirect_to root_path
	end

	def upvote
		@pin.upvote_by current_user
		redirect_to :back
	end

	private

	def pin_params
		params.require(:pin).permit(:title, :description, :image)
	end

	def find_pin
		@pin = Pin.find(params[:id])
	end

	def authorized_user
		if current_user.admin == false
	  		@pin = current_user.pins.find_by(id: params[:id])
	  		redirect_to pins_path, notice: "Not authorized to edit this pin" if @pin.nil?
	  	end
	  	# if @pin == nil and current_user.admin == false
	  	# 	redirect_to pins_path, notice: "Not authorized to edit this pin"
	  	# end
	end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pins_helper.rb
module PinsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Pinterwhore</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <meta name='viewport' content='width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no' />
</head>
<body>
	<nav class="navbar navbar-default">
		<div class="container">
			<div class="navbar-brand">
				<%= link_to "Pinterwhore", root_path, method: :get %>
			</div>

			<% if user_signed_in? %>
				<ul class="nav navbar-nav navbar-right">
					<li><%= link_to "New Pin", new_pin_path %></li>
					<li><%= link_to "Account", edit_user_registration_path %></li>
					<li><%= link_to "Sign Out", destroy_user_session_path, method: :delete %></li>
				</ul>
			<% else %>
				<ul class="nav navbar-nav navbar-right">
					<li><%= link_to "Sign Up", new_user_registration_path %></li>
					<li><%= link_to "Sign In", new_user_session_path %></li>
				</ul>
			<% end %>
		</div>
	</nav>

	<div class="container">
		<% flash.each do |name,msg| %>
			<%= content_tag :div, msg, class: "alert alert-info" %>
		<% end %>
		<%= yield %>
	</div>

</body>
</html>

app/views/pins/_form.html.erb
<%= simple_form_for @pin, html: { multipart: true } do |f| %>
	<% if @pin.errors.any? %>
		<div id="errors">
			<h2>
				<%= pluralize(@pin.errors.count, "error") %>
				prevented this Pin from saving
			</h2>
			<ul>
				<% @pin.errors.full_messages.each do |msg| %>
					<li><%= msg %></li>
				<% end %>
			</ul>
		</div>
	<% end %>

	<div class="form-group">
		<%= f.input :image, input_html: { class: 'form-control' } %>
	</div>

	<div class="form-group">
		<%= f.input :title, input_html: { class: 'form-control' } %>
	</div>

	<div class="form-group">
		<%= f.input :description, input_html: { class: 'form-control' } %>
	</div>

	<%= f.button :submit, class: "btn btn-primary" %>

<% end %>

app/views/pins/edit.html.erb
<div class="col-md-6 col-md-offset-3">
	<div class="row">
		<div class="panel panel-default">
			<div class="panel-heading">
				<h1>New Pin</h1>				
			</div>
			<div class="panel-body">
				<strong class="center">Current Image</strong>
				<br>
				<%= image_tag @pin.image.url(:medium) %>
				<br>
				<%= render 'form' %>			
			</div>
		</div>
	</div>
</div>

app/views/pins/index.html.erb
<div id="pins" class="transitions-enabled">
	<% @pins.each do |pin| %>
		<div class="box panel panel-default">
			<%= link_to (image_tag pin.image.url), pin %>
			<div class="panel-body">
				<h2><%= link_to pin.title, pin %></h2>		
				<p class="user">
					Submitted <%= time_ago_in_words(pin.created_at) %> ago by
					<%= pin.user.name %>
				</p>	
			</div>
		 </div>
	<% end %>
</div>
 

app/views/pins/new.html.erb
<div class="col-md-6 col-md-offset-3">
	<div class="row">
		<div class="panel panel-default">
			<div class="panel-heading">
				<h1>New Form</h1>				
			</div>
			<div class="panel-body">
				<%= render 'form' %>			
			</div>
		</div>
	</div>
</div>

app/views/pins/show.html.erb
<div id="pin_show" class="row">
	<div class="col-md-8 col-md-offset-2">
		<div class="panel panel-default">
			<div class="panel-heading pin_image">
				<%= image_tag @pin.image.url %>
			</div>
			<div class="panel-body">
				<h1><%= @pin.title %></h1>

				<p><%= @pin.description %></p>
			</div>
			<div class="panel-footer">
				<div class="row">
					<div class="col-md-6">
						<p class="user">
							Submitted <%= time_ago_in_words(@pin.created_at) %> ago by
							<%= @pin.user.email %>
						</p>
					</div>
					<div class="col-md-6">
						<div class="btn-group pull-right">
							<%= link_to like_pin_path(@pin), method: :put, class: "btn btn-default" do %>
								<span class="glyphicon glyphicon-heart">
									<%= @pin.get_upvotes.size %>
								</span>
							<% end %>
							
							<% if user_signed_in? %>
								<% if @pin.user == current_user %>
									<%= link_to "Edit", edit_pin_path, class: "btn btn-default" %>
									<%= link_to "Delete", pin_path, method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-default" %>
								<% elsif current_user.admin == true %>
									<%= link_to "Edit", edit_pin_path, class: "btn btn-default" %>
									<%= link_to "Delete", pin_path, method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-default" %>
								<% end %>
							<% end %>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>